// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/ModelOneProto/model.proto

package ModelOneProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ModelOneProto service

func NewModelOneProtoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ModelOneProto service

type ModelOneProtoService interface {
	FuncOne(ctx context.Context, in *FuncOneReq, opts ...client.CallOption) (*FuncOneRsp, error)
}

type modelOneProtoService struct {
	c    client.Client
	name string
}

func NewModelOneProtoService(name string, c client.Client) ModelOneProtoService {
	return &modelOneProtoService{
		c:    c,
		name: name,
	}
}

func (c *modelOneProtoService) FuncOne(ctx context.Context, in *FuncOneReq, opts ...client.CallOption) (*FuncOneRsp, error) {
	req := c.c.NewRequest(c.name, "ModelOneProto.FuncOne", in)
	out := new(FuncOneRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ModelOneProto service

type ModelOneProtoHandler interface {
	FuncOne(context.Context, *FuncOneReq, *FuncOneRsp) error
}

func RegisterModelOneProtoHandler(s server.Server, hdlr ModelOneProtoHandler, opts ...server.HandlerOption) error {
	type modelOneProto interface {
		FuncOne(ctx context.Context, in *FuncOneReq, out *FuncOneRsp) error
	}
	type ModelOneProto struct {
		modelOneProto
	}
	h := &modelOneProtoHandler{hdlr}
	return s.Handle(s.NewHandler(&ModelOneProto{h}, opts...))
}

type modelOneProtoHandler struct {
	ModelOneProtoHandler
}

func (h *modelOneProtoHandler) FuncOne(ctx context.Context, in *FuncOneReq, out *FuncOneRsp) error {
	return h.ModelOneProtoHandler.FuncOne(ctx, in, out)
}
